# YAML

jenkins:
    host: "172.24.100.13"
    baseUrl: "https://172.24.100.13"
    user: "alexander"
    token: "a8b17adf567c7213e095135e14ff9bdd"
    jobs:
        - {"job": "Selenium-Frontend-Mobile-mainSite", "short": "Mobile mainSite"}
        - {"job": "Selenium-Frontend-Mobile-Integration", "short": "Mobile Integration"}
        - {"job": "Selenium-Frontend-Desktop-mainSite", "short": "Desktop mainSite"}
        - {"job": "Selenium-Frontend-Desktop-Integration", "short": "Desktop Integration"}
        - {"job": "Selenium-Frontend-Desktop-Flash-Games-Python", "short": "Desktop Flash"}
        - {"job": "API-tests", "short": "API tests"}

