web:
  image: dashi
  ports:
    - "3000:3000"
  links:
    - redis
  volumes:
    - ./config.yml:/opt/web/config.yml

redis:
  image: redis
haproxy:
  image: tutum/haproxy
  links:
    - web
  environment:
    - BACKEND_PORT=3000
  ports:
    - "80:80"


