# YAML

jenkins:
    host: "<hostname-or-ip>"
    user: "<username>"
    token: "<userToken>"
    poll_interval: 10
    transport: 'http'
    jobs:
        - {"job": "<jenkins-job-name>", "short": "<shorter job description>"}
redis:
    host: "<hostname-or-ip>"
    port: 6379 
    db: 0
    expire_time: 30
server:
    port: 3000
    debug: True
